# Generated by Django 3.2 on 2022-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0003_auto_20210827_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(default='nothing.jpg', max_length=32),
            preserve_default=False,
        ),
    ]
