# Generated by Django 3.2 on 2022-05-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0004_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=128),
        ),
    ]
