# Generated by Django 3.2 on 2022-06-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0006_event_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
