# Generated by Django 4.0.5 on 2022-06-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0007_alter_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('unreviewed',
                                            'unreviewed'),
                                           ('unrelated',
                                            'unrelated'),
                                           ('different_versions',
                                            'different_versions'),
                                           ('duplicate',
                                            'duplicate')],
                                  max_length=20)),
                ('reviewed_at', models.DateTimeField()),
                ('existing_submission',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='possible_subsequent_duplicates',
                                   to='devolving_music.songsubmission')),
                ('new_submission',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='possible_prior_duplicates',
                                   to='devolving_music.songsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='duplicationflag',
            constraint=models.UniqueConstraint(
                fields=(
                    'existing_submission',
                    'new_submission'),
                name='unique_submission_pair'),
        ),
    ]
