# Generated by Django 4.1 on 2022-08-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0011_songcomparison_voter_songsubmission_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spotify_playlist_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
