# Generated by Django 4.1 on 2022-08-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolving_music', '0012_event_spotify_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spotify_playlist_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
