/* This file has been autogenerated.
DO NOT manually edit it.
Run `python manage.py transpile_models` to update it. */

export type User = {
  id: number,
  password: string,
  last_login: string,
  is_superuser: boolean,
  username: string,
  first_name: string,
  last_name: string,
  email: string,
  is_staff: boolean,
  is_active: boolean,
  date_joined: string,
}

export const Artist_platform = ['Spotify', 'YouTube', 'Soundcloud'] as const;

export type Artist = {
  id: number,
  name: string,
  platform: typeof Artist_platform[number],
  platform_id: string,
}

export type Song = {
  id: number,
  title: string,
  platform_id: string,
  artists: Artist[],
}

export type Event = {
  id: number,
  name: string,
  date: string,
  created_at: string,
  image: string,
  visible: boolean,
  allow_spotify: boolean,
  allow_youtube: boolean,
  allow_soundcloud: boolean,
}

export type SongSubmission = {
  id: number,
  event: Event,
  song: Song,
  submitter: User,
  created_at: string,
}

export type SongComparison = {
  id: number,
  first_submission: SongSubmission,
  second_submission: SongSubmission,
  voter: User,
  created_at: string,
  first_better: boolean,
  first_peakier: boolean,
  first_post_peakier: boolean,
}

export const DuplicationFlag_status = ['unreviewed', 'unrelated', 'different_versions', 'duplicate'] as const;

export type DuplicationFlag = {
  id: number,
  existing_submission: SongSubmission,
  new_submission: SongSubmission,
  status: typeof DuplicationFlag_status[number],
  reviewed_at: string,
}

